# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import mainsite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20181003_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinfo',
            name='api_base',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='manifest_domain',
            field=models.CharField(default=mainsite.utils.generate_random_fake_badge_connect_domain, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='privacy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='terms_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
