# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-02 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20181003_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinfo',
            name='api_base',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='manifest_domain',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='privacy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='terms_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
