# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import mainsite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20190201_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='manifest_domain',
            field=models.CharField(default=mainsite.utils.generate_random_fake_badge_connect_domain, max_length=254, unique=True),
        ),
    ]
